name: "meson: windows 2022"

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install meson ninja

      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64

      - name: Configure
        run: meson setup --warnlevel 3 --werror -Dlibxml2_cmake:werror=false -Dmaintainer-mode=false _build

      - name: capture shared meson configure
        uses: actions/upload-artifact@v4
        with:
          name: shared libxml2 configure
          path: |
            _build/subprojects/libxml2_cmake/meson.build
            _build/subprojects/libxml2_cmake/__CMake_build/cmake_trace.txt

      - name: Compile
        run: ninja -C _build

      - name: Test
        run: meson test -C _build

      - name: Configure static
        run: meson setup --warnlevel 3 --werror -Dlibxml2_cmake:werror=false --default-library static -Dmaintainer-mode=false _build_static

      - name: capture static meson configure
        uses: actions/upload-artifact@v4
        with:
          name: static libxml2 configure
          path: |
            _build_static/subprojects/libxml2_cmake/meson.build
            _build_static/subprojects/libxml2_cmake/__CMake_build/cmake_trace.txt

      - name: Compile static
        run: ninja -C _build_static

      - name: Test static
        run: meson test -C _build_static

      - name: capture meson log
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: libxml2-meson-logs
          path: |
            _build/meson-logs/meson-log.txt
            _build_static/meson-logs/meson-log.txt
